- input:
    xlsx: ../../../resources/wording.xlsx
    sheet: Wording
    start_row: 2
    mapping:
      ENGLISH : EN
      JAPANESE : JA
      ID: ID

  output:
    iOS_Header: ../../../ios/prizy.me/prizy.me/Constants/Wording.swift

    iOS_SINGLE:
      ENGLISH: ../../../ios/prizy.me/prizy.me/Resources/Localization/en.lproj/Localization.strings
      JAPANESE: ../../../ios/prizy.me/prizy.me/Resources/Localization/ja.lproj/Localization.strings

    iOS_PLURAL:
      ENGLISH: ../../../ios/prizy.me/prizy.me/Resources/Localization/en/Localization.plist
      JAPANESE: ../../../ios/prizy.me/prizy.me/Resources/Localization/ja/Localization.plist
