enum Wording: String {
    case WRD_ALERT_BUTTON_OK="alert_button_ok"
    case WRD_CANCEL="cancel"
    case WRD_CONNECTION_ERROR="connection_error"
    case WRD_EMAIL="email"
    case WRD_EMAIL_TEXT_HINT="email_text_hint"
    case WRD_ERROR_HEADER="error_header"
    case WRD_FAILED_HEADER="failed_header"
    case WRD_FORGOT_PASSWORD="forgot_password"
    case WRD_INCORRECT_PASSWORD_ERROR="incorrect_password_error"
    case WRD_LOGIN="login"
    case WRD_LOGOUT="logout"
    case WRD_PASSWORD="password"
    case WRD_PASSWORD_TEXT_HINT="password_text_hint"
    case WRD_RECOVER_PASSWORD="recover_password"
    case WRD_RECOVER_PASSWORD_ALERT_HEADER="recover_password_alert_header"
    case WRD_RECOVER_PASSWORD_ALERT_MSG="recover_password_alert_msg"
    case WRD_REMEMBER_ME="remember_me"
}
